### ISSUE TITLE
ErrorInfo.Message not displayed

### ISSUE THREAD

**Issue by mausch** [devlooped/dotnet-trx#85]
Hi and thanks for this project!

Given the following failing test:

```
public class FailingTest
{
    [Fact]
    public void Fails()
    {
        throw new Exception("This test fails!");
    }
}
```

The corresponding TRX file for this failing test says:

```xml
 <UnitTestResult executionId="04310b12-0c5b-4382-90ee-1b0f9f8ca416" testId="c0178bf2-d688-b0a3-ca4b-23adb1d13dad" testName="Elevate.Specs.Unit.App.FailingTest.Fails" computerName="ip-172-16-31-183" duration="00:00:00.0004537" startTime="2025-04-28T06:47:07.0942795+00:00" endTime="2025-04-28T06:47:07.0942798+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="04310b12-0c5b-4382-90ee-1b0f9f8ca416">
   <Output>
     <ErrorInfo>
       <Message>System.Exception : This test fails!</Message>
       <StackTrace>   at Elevate.Specs.Unit.App.FailingTest.Fails() in /codebuild/output/src2083754727/src/actions-runner/_work/elevate-app/elevate-app/src/Elevate.Specs.Unit/App/FailingTest.cs:line 11
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)</StackTrace>
     </ErrorInfo>
   </Output>
 </UnitTestResult>
```

but the build summary generated by dotnet-trx only includes the stack trace not the message:

![Image](https://github.com/user-attachments/assets/6feeaf51-7431-43a1-994b-c721cd59385f)

The github action step is:

```
    - name: Test report
      if: always()
      run: |
        dotnet tool install dotnet-trx --version 0.5.2
        dotnet trx --recursive --output --gh-summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
